name: todo_app
description: "An offline-first to-do application with Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Permissions
  permission_handler: ^11.0.1

  # Image Picker
  image_picker: ^1.0.4

  # Routing
  go_router: ^12.1.3

  # Utils
  path_provider: ^2.1.2
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Integration testing
  integration_test:
    sdk: flutter

  # Database testing
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
